### PR TITLE
Learn react

### PR DESCRIPTION
**Pull request by nasirmovlamov**
Translating home page main content.

### CODE REVIEW

**Comment by nasirmovlamov** [comment]
@GasimGasimzada

**Comment by azizaismayilova** [comment]
Hi @nasirmovlamov ! can you please add your name in translation progress list according which page you doing? So nobody will work on the same content :)

**Comment by nasirmovlamov** [comment]
Hi @azizaismayilova sure

**Comment by nasirmovlamov** [comment]
@GasimGasimzada  @azizaismayilova  i updated content based on dictionary

**Comment by GasimGasimzada** [comment]
@nasirmovlamov According to React team, these pages -- homepage, header, and footer will go through invasive changes, which will result in significant amount of merge conflicts when the changes are synced with this repository. This will result in either spending a lot of time fixing the conflicts or rewriting this from the beginning again. In order to not duplicate this work, I would like you to close all your PRs with regards to UI changes and do translations of other translations (anything in "Main Content" section in https://github.com/reactjs/az.react.dev/issues/376).

> We suggest to leave most of the UI translation until the end. We plan to do some invasive changes to the website folder layout and components, so postponing this until your translation is almost complete would make it easier to merge the changes from our side later. It might make sense to translate the homepage above the fold early, but leave the rest for later. As individual pages get translated, you can change the page titles in the corresponding sidebar files. Finally, when you're translating the navigation, make sure to test both desktop and mobile layouts.

**Comment by nasirmovlamov** [comment]
@GasimGasimzada for sure

**Pull request closed without merging**
